import { Theme } from '@/theme';
import { CSSProperties } from 'react';

export const createStyles = (theme: Theme): CSSProperties => {
  return {
    '--color-primary': theme.colors.primary,
    '--color-secondary': theme.colors.secondary,
    '--color-background': theme.colors.primaryBg,
    '--color-surface': theme.colors.secondaryBg,
    '--color-text': theme.colors.primaryText,
    '--color-textSecondary': theme.colors.secondaryText,
    '--color-error': theme.colors.error || theme.colors.primaryText,
    '--color-success': theme.colors.success || theme.colors.darkGreen,
    '--color-warning': theme.colors.warning || theme.colors.blue,
    '--color-lightGreen': theme.colors.lightGreen,
    '--color-green': theme.colors.green,
    '--color-darkGreen': theme.colors.darkGreen,
    '--color-blue': theme.colors.blue,
    '--color-darkBlue': theme.colors.darkBlue,
    '--color-white': theme.colors.white,
    '--color-black': theme.colors.black,
    '--color-lightGray': theme.colors.lightGray,
    '--color-darkGray': theme.colors.darkGray,
    '--color-offWhite': theme.colors.offWhite,
    '--spacing-xs': theme.spacing.xs,
    '--spacing-sm': theme.spacing.sm,
    '--spacing-md': theme.spacing.md,
    '--spacing-lg': theme.spacing.lg,
    '--spacing-xl': theme.spacing.xl,
    '--spacing-xxl': theme.spacing.xxl,
    '--font-size-xs': theme.fonts.sizes.xs,
    '--font-size-sm': theme.fonts.sizes.sm,
    '--font-size-md': theme.fonts.sizes.md,
    '--font-size-lg': theme.fonts.sizes.lg,
    '--font-size-xl': theme.fonts.sizes.xl,
    '--font-size-xxl': theme.fonts.sizes.xxl,
    '--font-size-xxxl': theme.fonts.sizes.xxxl,
    '--spacing-maxWidth': theme.spacing.maxWidth,
    '--spacing-maxl': theme.spacing.maxl,
    '--font-family-sans': theme.fonts.families.sans,
    '--font-family-quicksand': theme.fonts.families.quicksand,
    '--font-family-heading': theme.fonts.families.quicksand,
    '--font-family-body': theme.fonts.families.sans,
    '--font-family-serif': theme.fonts.families.serif,
    '--font-family-mono': theme.fonts.families.mono,
    '--font-weight-thin': theme.fonts.weights.thin,
    '--font-weight-light': theme.fonts.weights.light,
    '--font-weight-normal': theme.fonts.weights.normal,
    '--font-weight-medium': theme.fonts.weights.medium,
    '--font-weight-semibold': theme.fonts.weights.semibold,
    '--font-weight-bold': theme.fonts.weights.bold,
  } as CSSProperties;
};

